spring.application.name=user-json-service
#
server.port=8080


s3.access.key=DO801YUGT6NXNNBTAY4W
s3.secret.key=OzzySogJYFaA6+egEN28bb/RQ48PX06h3K/UDIvkUDI
s3.endpoint=https://sfo3.digitaloceanspaces.com
s3.bucket=lab-bucket6
soap.service.url=https://coral-app-ftsk5.ondigitalocean.app
spring.datasource.url=jdbc:postgresql://db-postgresql-nyc3-24333-do-user-34793481-0.f.db.ondigitalocean.com:25060/defaultdb?sslmode=require
spring.datasource.username=doadmin
spring.datasource.password=AVNS_e-qyMF192u1amz9SnQP
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect