spring.application.name=user-json-service
#
server.port=8081
#
## H2 Database
#spring.datasource.url=jdbc:h2:mem:profiledb
#spring.datasource.username=sanaa
#spring.datasource.password=0819
#
## JPA
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.show-sql=true
#
## H2 Console
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#
## SOAP Service URL (for token validation)
soap.service.url=${SOAP_SERVICE_URL}
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect